name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.14.0-alpha.5'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - run: python -m pytest tests/ 